Models/Newsfeed.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace meldboek.Models
{
    public class Newsfeed
    {
        public IEnumerable<Newspost> Post { get; set; }
        public IEnumerable<Group> Group { get; set; }
        public IEnumerable<Person> Friend { get; set; }
    }
}

Controllers/AdminController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

using meldboek.Models;
using Microsoft.AspNetCore.Mvc;
using Neo4j.Driver;
using Newtonsoft.Json;

namespace meldboek.Controllers
{
    public class AdminController : Controller
    {
        public IDriver Driver { get; set; }

        public IActionResult Index()
        {
            return View();
        }
        public IActionResult CreateAccount()
        {
            return View();
        }

        public IActionResult LogIn(string email, string password)
        {

            {
                if (email == "admin" && password == "admin")
                {
                    Response.Redirect("LogIn");
                }
            }



            return View();

        }
        public IActionResult CreateGroups(string Groepnaam, string ManagerID)
        {
            if (Groepnaam != null)
            {
                int groupId = GetMaxGroupId();
                Group g = new Group(groupId, Groepnaam);

                var r = ConnectDb("CREATE (g:Group {GroupId: " + g.GroupId + ", GroupName: '" + g.GroupName + "' }) RETURN g");

                r.Wait();
                //dit is om het de Neo4J ID te pakken
                // var GroupLong = r.Result[0].Id; 
                // int GroupId = unchecked((int)GroupLong);


                var r2 = ConnectDb("MATCH (p:Person),(g:Group) WHERE p.PersonId = " + ManagerID + " AND g.GroupId = " + groupId + " CREATE(p) -[r: IsOwner]->(g) RETURN p, g");
                r2.Wait();

            }


            return View();




        }

        public int GetMaxGroupId()
        {
            int returnId = 0;
            // GetMaxPostId pakt een id die nog niet gebruikt wordt
            Random rnd = new Random();


            while (true)
            {
                returnId = rnd.Next(1000001, 999999999);
                var r = ConnectDb("MATCH (n:Group) WHERE n.GroupId =" + returnId + " return n;");
                r.Wait();
                if (r.Result.Count == 0)
                {
                    return returnId;
                }
            }
        }

        public async Task<List<INode>> ConnectDb(string query)
        {
            Driver = CreateDriverWithBasicAuth("bolt://localhost:11005", "neo4j", "1234");
            List<INode> res = new List<INode>();
            IAsyncSession session = Driver.AsyncSession(o => o.WithDatabase("neo4j"));

            try
            {
                res = await session.ReadTransactionAsync(async tx =>
                {
                    var results = new List<INode>();
                    var reader = await tx.RunAsync(query);

                    while (await reader.FetchAsync())
                    {
                        results.Add(reader.Current[0].As<INode>());

                    }

                    return results;
                });


            }

            finally
            {
                await session.CloseAsync();

            }
            return res;

        }
        public IDriver CreateDriverWithBasicAuth(string uri, string Person, string password)
        {
            return GraphDatabase.Driver(new Uri(uri), AuthTokens.Basic(Person, password));
        }

    }
}

Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Web.Http;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using meldboek.Models;
using Neo4jClient;
using Neo4j.Driver;
using Neo4jClient.Cypher;
using Newtonsoft.Json;

namespace meldboek.Controllers
{
    public class HomeController : Controller
    {
        public IDriver Driver { get; set; }
        public IGraphClient GraphClient { get; set; }



        public IActionResult Index()
        {
            // var results = ConnectDb("CREATE (n:Person { name: 'Yas2', title: 'Developer' }) RETURN n");
            // var results = ConnectDb("MATCH (a:Person) RETURN a");


            // DIT IS ALLEMAAL OM TE TESTEN

            // var Person1 = GetPerson(1);
            // var email = Person1.Email;
            // var id = Person1.PersonId;
            // var name = Person1.FirstName;
            // var namelast = Person1.LastName;
            // Console.WriteLine(email + id + name + namelast);

            //   var result = AddFriend(1, 5);
            // var result2 = AddFriend(2, 3);
            //  Console.WriteLine(result.ToString());
            // Console.WriteLine(result2.ToString());

            // AcceptFriend(GetPerson(1),GetPerson(2));

            //AddPersonToGroup(1, 1);
            // DeletePersonFromGroup(1, 1);
          

            return View();
        }

        


        public async Task<List<INode>> ConnectDb(string query)
        {
            Driver = CreateDriverWithBasicAuth("bolt://localhost:7687", "neo4j", "1234");
            List<INode> res = new List<INode>();
            IAsyncSession session = Driver.AsyncSession(o => o.WithDatabase("neo4j"));

            try
            {
                res = await session.ReadTransactionAsync(async tx =>
                {
                    var results = new List<INode>();
                    var reader = await tx.RunAsync(query);

                    while (await reader.FetchAsync())
                    {
                        results.Add(reader.Current[0].As<INode>());

                    }

                    return results;
                });


            }

            finally
            {
                await session.CloseAsync();

            }
            return res;

        }


        // public async Task<List<NodeResult>> ConnectDb(string query)
        // {
        //     Driver = CreateDriverWithBasicAuth("bolt://localhost:7687", "neo4j", "1234");
        //     List<NodeResult> res = new List<NodeResult>();
        //     IAsyncSession session = Driver.AsyncSession(o => o.WithDatabase("neo4j"));

        //     try
        //     {
        //         res = await session.ReadTransactionAsync(async tx =>
        //         {
        //             var results = new List<NodeResult>();
        //             var reader = await tx.RunAsync(query);

        //             while (await reader.FetchAsync())
        //             {
        //                 var obj = new NodeResult()
        //                 {
        //                     Result = reader.Current[0],
        //                     node = reader.Current[0].As<INode>()
        //                 };

        //                 results.Add(obj);
        //             }

        //             return results;
        //         });
        //         var node = res[0].As<INode>();
        //         Console.WriteLine(node);

        //     }

        //     finally
        //     {
        //         await session.CloseAsync();

        //     }
        //     return res;

        // }




        public IDriver CreateDriverWithBasicAuth(string uri, string Person, string password)
        {
            return GraphDatabase.Driver(new Uri(uri), AuthTokens.Basic(Person, password));
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PersonController.cs
using System;
using System.Web;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using meldboek.Models;
using Neo4j.Driver;
using Newtonsoft.Json;
using Microsoft.EntityFrameworkCore.Metadata.Internal;
using Neo4jClient;
using System.Collections;
using System.Reflection;
using System.Dynamic;
using System.Xml;
using meldboek.ViewModels;
using System.Globalization;
using Microsoft.AspNetCore.Http;

namespace meldboek.Controllers
{
    public class PersonController : Controller
    {
        public IDriver Driver { get; set; }

        public IActionResult Index()
        {
            return View();
        }

        [Route("Person/GroepenManagen")]
        public IActionResult GroepenManagen()
        {
            dynamic model = new ExpandoObject();
            model.OwnedGroups = GetOwnedGroups();

            model.GroupsManagement = null;

            return View(model);
        }

        public IActionResult ManageGroup(int GroupId)
        {
            dynamic model = new ExpandoObject();
            model.OwnedGroups = GetOwnedGroups();

            model.GroupsManagement = GetGroupsManagement(GroupId);

            return View("GroepenManagen", model);
        }
        public IActionResult AddFile()
        {
            return View();
        }
        [HttpPost]
        public async Task<IActionResult> FileUpload(IFormFile file, int NewspostId)
        {
            //would do Newspost post and then post.postid later

            //get person logged in but for now just person 1 or even post.creator
            Person person = GetPerson(1);

            var folder = "/Users/yasemin/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-a67a9b4b-e0cb-404c-99ce-fccc6509622f/installation-4.0.2/import/" + person.PersonId.ToString() + "/" + NewspostId.ToString();
            if (!System.IO.Directory.Exists(folder))
            {
                System.IO.Directory.CreateDirectory(folder);
            }
            if (file.Length > 0)
            {

                var filename = file.FileName;


                var path = "/Users/yasemin/Library/Application Support/Neo4j Desktop/Application/neo4jDatabases/database-a67a9b4b-e0cb-404c-99ce-fccc6509622f/installation-4.0.2/import/" + person.PersonId.ToString() + "/" + NewspostId.ToString() + "/" + filename;

                using (var stream = System.IO.File.Create(path))
                {
                    await file.CopyToAsync(stream);
                }

            }
        
            //just to test

            return RedirectToAction("AddFile");
        }
        [HttpGet("download")]
        public IActionResult GetDownload(string link)
        {
            //not done yet
            var net = new System.Net.WebClient();
            var data = net.DownloadData(link);
            var content = new System.IO.MemoryStream(data);
            var contentType = "APPLICATION/octet-stream";
            return File(content, contentType);
        }

        //[Route("Person/Profile")]
        public IActionResult Profile()
        {
            //grab a random person out of the DB untill be have the claims
            int personid = 1;
            List<PersonInfo> personInfos = new List<PersonInfo>();
            List<Person> Relations = GetRelationsById(personid);
            Person person = GetPerson(personid);
            Profile profile = new Profile();
            profile.Name = person.FirstName + " " + person.LastName;
            profile.Email = person.Email;
            profile.Relaties = Relations;
            profile.PersonId = person.PersonId;

            foreach (var rela in Relations)
            {
                var statusreq = CheckFriendRequeststatus(person.PersonId, rela.PersonId);
                if (statusreq == "requested")
                {
                    personInfos.Add(new PersonInfo()
                    {
                        Person = rela,
                        Status = statusreq
                    });
                }
                else if (statusreq == "Friends")
                {
                    personInfos.Add(new PersonInfo()
                    {
                        Person = rela,
                        Status = "IsFriendsWith"
                    });
                }

                else personInfos.Add(new PersonInfo()
                {
                    Person = rela,
                    Status = CheckFriendStatus(person.PersonId, rela.PersonId)
                });

            };
            profile.PersonInfos = personInfos;


            return View(profile);
        }

        public IActionResult CreateAccount(string firstname, string lastname, string email, string password, string password2)
        {
            //maakt Person als alles ingevoerd is en wachtwoord klopt
            if (firstname != null & lastname != null & email != null & password != null & password == password2)
            {

                int persId = GetMaxPersonId();
                //stuurt Person naar database
                var r = ConnectDb("CREATE (p:Person { PersonId: " + persId + ", FirstName: '" + firstname + "', LastName: '" + lastname + "' ,Email: '" + email + "', Password: '" + password + "' }) RETURN p");
                r.Wait();
                return View();
            }
            else
            {
                //password incorrect
                return View();
            }


        }
        

        public IActionResult Home()
        {
            return View();
        }

        public IActionResult Newsfeed()
        {
            // Default page is page with filter "Algemeen", which displays all the posts that are not posted in a group.
            TempData["Page"] = "Algemeen";

            // Before returning the view of the newsfeed, all the newsposts and groups need to be pulled from the database.
            dynamic model = new ExpandoObject();
            model.Post = GetFeed();

            model.Group = GetGroups();
            model.Friend = GetFriends();

            return View(model);
        }

        public IActionResult FilteredNewsfeed(string filter)
        {
            // FilteredNewsfeed returns a newsfeed with a filter depending on what the Person chose.

            if (filter == "Algemeen")
            {
                // Filter "Algemeen" is the default value, so this redirects to the original state of the newsfeed.
                TempData["Page"] = filter;
                return RedirectToAction("Newsfeed");
            }
            else if (filter == "Vrienden")
            {
                // If the Person chose the filter "Vrienden", GetFriendPosts() is used to get the correct posts.
                dynamic model = new ExpandoObject();

                model.Post = GetFriendPosts();

                model.Group = GetGroups();
                model.Friend = GetFriends();

                TempData["Page"] = filter;
                return View("Newsfeed", model);
            }
            else
            {
                // If the chosen filter is neither "Algemeen" or "Vrienden" the Person has chosen a filter for group [groupname].
                dynamic model = new ExpandoObject();

                model.Post = GetGroupPosts(filter);

                model.Group = GetGroups();
                model.Friend = GetFriends();

                TempData["Page"] = filter;
                return View("Newsfeed", model);
            }
        }

        public IActionResult Groepen()
        {
            return View(GetGroupsData());
        }

        public IActionResult Personlist()
        {
            // Default page is page with filter "Alle gebruikers", which displays all the Persons from the database.
            TempData["Page"] = "Alle gebruikers";
            return View(GetPersonlist());
        }

        public IActionResult FilteredPersonlist(string filter)
        {
            // FilteredPersonlist returns a personlist with a filter depending on what the Person chose.

            if (filter == "Alle gebruikers")
            {
                // Filter "Alle gebruikers" is the default value, so this redirects to the original state of the personlist.
                TempData["Page"] = filter;
                return RedirectToAction("Personlist");
            }
            else if (filter == "Vrienden")
            {
                // If the Person chose the filter "Vrienden", GetFriends() is used to get the correct Persons.

                TempData["Page"] = filter;
                return View("Personlist", GetFriends());
            }
            else
            {
                return RedirectToAction("Personlist");
            }
        }

        public int GetMaxPostId()
        {
            int returnId = 0;
            // GetMaxPostId pakt een id die nog niet gebruikt wordt
            Random rnd = new Random();


            while (true)
            {
                returnId = rnd.Next(1000001, 999999999);
                var r = ConnectDb("MATCH (n:Post) WHERE n.PostId =" + returnId + " return n;");
                r.Wait();
                if (r.Result.Count == 0)
                {
                    return returnId;
                }
            }
        }
        public int GetMaxPersonId()
        {
            int returnId = 0;
            // GetMaxPostersonId pakt een id die nog niet gebruikt wordt
            Random rnd = new Random();


            while (true)
            {
                returnId = rnd.Next(1000001, 999999999);
                var r = ConnectDb("MATCH (n:Person) WHERE n.PersonId =" + returnId + " return n;");
                r.Wait();
                if (r.Result.Count == 0)
                {
                    return returnId;
                }
            }


        }

        [HttpPost]
        public async Task<IActionResult> AddPost(string title, string description, string group)
        {

Views/Person/AddFile.cshtml
<form action="FileUpload" method="post" enctype="multipart/form-data">
  
  <label for="file">Filename: </label>
  <input type="file" name="file" id="file" /><br>
    <label >Post Id: </label>

  <input type="string" required name = NewspostId id="NewspostId"><br>

  <input type="submit" value = "Upload" />
</form>

Views/Person/GroepenManagen.cshtml
@{
    ViewData["Title"] = "Groepen beheren";
}

@model dynamic

<!DOCTYPE html>
<html>
<head>
    <link rel="stylesheet" type="text/css" href="~/css/Topbar_Sidenav.css">
    <style>
        #create-groups {
            padding: 10px;
            text-decoration: none;
            color: #0000ff;
            font-size: 22px;
            transition: 0.2s;
        }

        #create-groups:hover {
            color: #b3b3ff;
        }

        #Add-Delete-PersonToGroup {
            /* width: 320px; */
            padding: 15px;
            border: 2px solid #ffed00;
            margin: 50px 0px 40px 0px;
        }

        body {
            font-family: "Trebuchet MS", "Lucida Sans Unicode", "Lucida Grande",
            "Lucida Sans", Arial, sans-serif;
        }

        .group-options a {
            font-size: 18px;
            font-family: "Trebuchet MS", sans-serif;
        }

        input[type="submit"] {
            font-family: "Trebuchet MS", sans-serif;
            background-color: #ffed00;
            color: white;
            font-size: 18px;
            border-radius: 25px;
            padding: 10px 15px;
            border: none;
            cursor: pointer;
            transition: 0.2s;
        }

        input[type="submit"]:hover {
            background-color: #fff9a6;
        }

        .topbar {
            background-color: #ffed00;
        }

        .navbtn {
            background-color: #ffed00;
        }

        .overlay {
            background-color: #ffed00; 
        }

        .overlay a:hover, .overlay a:focus, .logout a:hover, .logout a:focus {
            color: #fff9a6;
        }

        .content {
            padding-top: 100px;
            width: 90%;
        }

        .groups {
            position: fixed;
            float: left;
            width: 180px;
            height: 550px;
            padding: 80px 30px 0px 40px;
            border-right: 2px solid #ffed00;
            overflow-y: auto;
        }

        .groups a {
            color: #000000;
            font-size: 24px;
            text-decoration: none;
            display: block;
            padding-bottom: 15px;
            transition: 0.2s;
            word-wrap: break-word;
        }

        .groups a:hover {
            color: #fff9a6;
        }

        .group-options {
            padding-top: 40px;
            margin-left: 350px;
        }

        select {
            font-family: 'Trebuchet MS', sans-serif;
            font-size: 18px;
            margin: 15px 0px 20px 0px;
            padding: 5px;
        }

        option {
            font-family: 'Trebuchet MS', sans-serif;
            font-size: 18px;
            padding: 5px;
        }

        input {
            font-family: 'Trebuchet MS', sans-serif;
            font-size: 18px;
            margin-bottom: 10px;
        }
    </style>
</head>
<body>
    <div class="topbar">
        <span class="navbtn" onclick="nav()">&#9776; </span>
        <h1 style="width: 57%;">Beheer groepen</h1>
        <a href="@Url.Action("Profile")"><img id="acc-icon" src="@Url.Content("~/Content/account.png")" /></a>
    </div>

    <div id="nav" class="overlay">
        <div class="overlay-content">
            <a href="@Url.Action("Newsfeed")">Nieuws</a> 
            <br>
            <a href="@Url.Action("ForumHome", "Forum")">Forums</a>
            <br>
            <a href="@Url.Action("Index", "Chat")">Chat</a>
            <br>
            <a  href="@Url.Action("Groepen")">Groepen</a>
            <br>
            <a href="@Url.Action("Personlist")">Gebruikers</a>
        </div>
        <div class="logout"><a onclick="nav()" href="#logout">Log uit</a></div>
    </div>
    <div class="content">
        <div class="groups">
           @if (Model.OwnedGroups.Count != 0)
            {
               @foreach (var group in Model.OwnedGroups)
                {
                    <a href="@Url.Action("ManageGroup", new { GroupId = group.GroupId })">@group.GroupName</a>
                }
            } else
            {
                <a>Je beheert nog geen groepen</a>
            }

        </div>

        <div class="group-options">
            <a id="create-groups" href="@Url.Action("Groepen")">&#8592; Groepen</a><a id="create-groups" href="@Url.Action("CreateGroups", "Admin")">Groep maken &#8594;</a>

           @if (Model.GroupsManagement != null)
            {
               @foreach (var group in Model.GroupsManagement)
                {
                    <div id="Add-Delete-PersonToGroup">
                        <a>Voeg een nieuw lid toe aan @group.Group.GroupName</a>
                        <form asp-action="AddPersonToGroup" method="post">
                            <input type="hidden" name="GroupId" value="@group.Group.GroupId">

                            <select id="PersonId" name="PersonId">

                                @foreach (var nonmember in group.NonMembers)
                                 {
                                    <option value="@nonmember.PersonId">@nonmember.FirstName @nonmember.LastName</option>
                                 }

                            </select><br>

                            <input type="submit" value="Toevoegen" id="submit">
                        </form>
                    </div>

                    <div id="Add-Delete-PersonToGroup">
                        <a>Verwijder een groepslid uit @group.Group.GroupName</a>
                        <form asp-action="DeletePersonFromGroup" method="post">
                            <input type="hidden" name="GroupId" value="@group.Group.GroupId">
      
                            <select id="PersonId" name="PersonId">

                                @foreach (var member in group.Group.Members)
                                 {
                                    <option value="@member.PersonId">@member.FirstName @member.LastName</option>
                                 }

                            </select><br>

                            <input type="submit" value="Verwijderen" id="submit">
                        </form>
                    </div>
                }
            }
        </div>
    </div>
</body>
</html>

Views/Person/Personlist.cshtml
@{
    ViewData["Title"] = "Gebruikers";
}

@model IEnumerable<PersonInfo>

<!DOCTYPE html>
<html>
    <head>
        <link rel="stylesheet" type="text/css" href="~/css/Topbar_Sidenav.css">
        <script type="text/javascript" src="~/js/site.js"></script>
        <style>
            body {
                font-family: 'Trebuchet MS', sans-serif;
                background-color: #ffffff;
            }

            .topbar {
                background-color: #e947ff;
            }

            .navbtn {
                background-color: #e947ff;
            }

            .overlay {
                background-color: #e947ff;
            }

            .overlay a:hover, .overlay a:focus, .logout a:hover, .logout a:focus {
                color: #f4a3ff;
            }

            .personlist-content {
                width: 100%;
                overflow: hidden;
                padding-top: 100px;
                padding-bottom: 50px;
            }

            /* options list */
            .options {
                position: fixed;
                float: left;
                width: 180px;
                height: 550px;
                padding: 80px 30px 0px 40px;
                border-right: 2px solid #e947ff;
                overflow-y: auto;
            }

            .options a {
                color: #000000;
                font-size: 24px;
                text-decoration: none;
                display: block;
                padding-bottom: 15px;
                word-wrap: break-word;
                transition: 0.2s;
            }

            .options a:hover {
                 color: #f4a3ff;
            }

            .page-title {
                font-size: 28px;
                padding-bottom: 20px;
            }

            /* Persons list */
            .person-list {
                padding-top: 40px;
                margin-left: 340px;
            }

            /* Single person */
            .person {
                width: 90%;
                overflow: hidden;
                border-bottom: 1px solid #e947ff;
            }

            /* Person content consists of name (h1) and friend/unfriend options (a). */
            .person-content {
                float: left;
                width: 80%;
            }

            .person-content h1 {
                font-size: 22px;
                padding-bottom: 10px;
                padding-top: 20px;
            }

            .person-options {
                margin-top: 20px;
                margin-left: 83%;
            }

            .person-options a {
                text-decoration: none;
                font-size: 20px;
            }

            #add-accept-friend {
                color: #00ff00;
                transition: 0.2s;
                display: block;
            }

            #add-accept-friend:hover {
                color: #b3ffb3;
            }

            #delete-deny-friend {
                color: #ff0000;
                transition: 0.2s;
            }

            #delete-deny-friend:hover {
                color: #ffb3b3;
            }
        </style>
    </head>
    <body>
        <!-- Colored bar at the top of the page -->
        <div class="topbar">

            <!-- The button that opens the sidemenu -->
            <span class="navbtn" onclick="nav()">&#9776; </span>

            <!-- Page title -->
            <h1>Gebruikers</h1>

            <!-- Account information button -->
            <a href="@Url.Action("Profile")"><img id="acc-icon" src="@Url.Content("~/Content/account.png")"/></a>
        </div>

        <!-- Sidemenu overlay -->
        <div id="nav" class="overlay">
            <div class="overlay-content">
                <a href="@Url.Action("Newsfeed")">Nieuws</a>
                <br>
                <a href="@Url.Action("ForumHome","Forum")">Forums</a>
                <br>
                <a href="@Url.Action("Index", "Chat")">Chat</a>
                <br>
                <a href="@Url.Action("Groepen")">Groepen</a>
                <br>
                <p style="color: #f4a3ff;">Gebruikers</p>
            </div>
            <div class="logout"><a onclick="nav()" href="#logout">Log uit</a></div>
        </div>

        <!-- All the actual content of the page -->
        <div class="personlist-content">

            <!-- Personlist options -->
            <div class="options">
                <a href="@Url.Action("FilteredPersonlist", new { filter = "Alle gebruikers" })">Alle gebruikers</a>
                <a href="@Url.Action("FilteredPersonlist", new { filter = "Vrienden"})">Vrienden</a>
            </div>

            <div class="person-list">
                <h1 class="page-title">@TempData["Page"]</h1>

                <!-- Single person attribute; Here all the posts from GetPersonlist() or FilteredPersonlist() are put on the page. -->
                @foreach (var person in Model)
                {
                    <div class="person">
                        <div class="person-content">
                            <h1>@person.Person.FirstName @person.Person.LastName</h1>
                        </div>

                        @if (person.Status == "")
                        {
                            <div class="person-options">
                                <a id="add-accept-friend" href="@Url.Action("Friend", new { FriendId = person.Person.PersonId })">Vriend toevoegen</a>
                            </div>
                        }
                    
                        @if (person.Status == "FriendPending")
                        {
                            <div class="person-options">
                                <a style="color: #0000ff;">In behandeling</a>
                            </div>
                        }

                        @if (person.Status == "FriendPendingRequest")
                        {
                            <div class="person-options" style="margin-top: 10px;">
                                <a id="add-accept-friend" href="@Url.Action("AcceptFriend", new { PersonRequestedId = person.Person.PersonId, PersonAcceptedId = 1, Page = "Personlist" })">Verzoek accepteren</a>
                                <a id="deny-delete-friend" href="@Url.Action("RefuseFriendReq", "Person", new { PersonId = person.Person.PersonId, page = "Personlist" })">Vriend afwijzen</a>
                            </div>
                        }

                        @if (person.Status == "IsFriendsWith")
                        {
                            <div class="person-options">
                                <a id="delete-deny-friend" href="@Url.Action("DeleteFriend", new { FriendId = person.Person.PersonId, Page = @TempData["Page"] })">Vriend verwijderen</a>
                            </div>
                        }

                    </div>
                }

            </div>
        </div>
    </body>
</html>